### ISSUE TITLE
making the permissions for the spigot server is not working

### ISSUE THREAD

**Issue by Ph4ntomX** [weaondara/BungeePerms#374]
so when I try to put a non-bungee plugin permission onto the default group it does not work. as in the FAQ, it says that it's most likely that I have not set bungeecord to true, but I have and I also put the server "lobby" as the server. I tried it on my test account and it still does not work.

"Steps to reproduce"

I did the command
/bungeeperms group Builder addperm essentials.afk lobby

**Expected behavior**
I expected that my test account will be able to do /afk

**Comment by aurorasmiles** [comment]
Did you install BungeePerms on that server and set the permission there?

**Comment by Ph4ntomX** [comment]
which servers? the spigot servers or the bungee server?

**Comment by aurorasmiles** [comment]
The server where the permissionb isn't working. For example if it is a Spigot plugin BungeePerms has to be installed on the Spigot server as well & the permission has to be set there (unless you are using a database instead of yml, then it doesn't matter where you set the permission as long as BungeePerms on every server has the same database configured)

**Comment by aurorasmiles** [comment]
No answer, in my tests everything was working fine. For support please use discord
